name: tsv_merge
description: Fast merge of TSV table with equal number of rows.
keywords:
    - tsv

tools:
  - shell commands (sed, paste, tail)

input:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - tables:
      type: list of files
      description: |
          List of input tsv files, should have the same number of rows

output:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      descrption: |
          output tsv file with merged columns
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
    - "@agalitsyna"
