name: redc-env
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.7
    - hisat2
    - trimmomatic
    - fastuniq
    - biopython
    - bedtools=2.29.2
    - numpy
    - h5py
    - pandas
    - pyfaidx
    - htslib
    - coreutils=8.31
    - cooler
